# frozen_string_literal: true

# Conformance-probe pipeline (docs/conformance/SPEC.md).
#
#   rake conformance:ingest DUMP=<file-8994 export> ENV=<name> [BACKEND=] [SUBSET=] [PACKAGES=]
#   rake conformance:probe  TARGET=<fingerprint.yml> [REQUIRED=<reference.yml>]
#
# `ingest` is the capture-side step (needs a raw broker dump on disk);
# `probe` is the CI-side step (needs only committed fingerprints).

namespace :conformance do
  # Fingerprint corpus location. Overridable via FINGERPRINTS_DIR= so the
  # tasks can serve other checkouts/gems (vista-rpc extraction seam);
  # defaults to this repo's data/fingerprints for existing callers.
  FINGERPRINTS_DIR = ENV["FINGERPRINTS_DIR"] ? File.expand_path(ENV["FINGERPRINTS_DIR"]) : File.expand_path("../../data/fingerprints", __dir__)

  desc "Ingest a file-8994 broker dump into data/fingerprints/<ENV>.yml " \
       "(DUMP=, ENV=, BACKEND=iris_rpms, optional SUBSET= allowlist, CAPTURED_AT=, NOTE=, " \
       "PACKAGES=<packages_9_4.txt> for the #9.4 versions face; " \
       "RELEASE= + DAT_SHA= stamp a per-rung reference for references/)"
  task :ingest do
    require "yaml"
    require "date"
    require "set"
    require "fileutils"
    require "rpms_rpc/conformance/package_dump"

    dump_path = ENV["DUMP"] or abort "conformance:ingest requires DUMP=<file-8994 export>"
    env_name = ENV["ENV"] or abort "conformance:ingest requires ENV=<fingerprint name>"
    backend = ENV["BACKEND"] || "iris_rpms"
    captured_at = ENV["CAPTURED_AT"] || Date.today.iso8601

    # Dump lines are caret-delimited file-8994 records:
    #   NAME^TAG^ROUTINE^PARAM^RETURN^...
    total = 0
    rpcs = {}
    File.foreach(dump_path) do |line|
      line = line.chomp
      next if line.empty?

      total += 1
      name, tag, routine, _param, return_type = line.split("^")
      meta = { "tag" => tag, "routine" => routine }
      meta["return_type"] = return_type unless return_type.nil? || return_type.empty?
      rpcs[name] = meta
    end

    # PACKAGE #9.4 versions face (optional): a packages_9_4.txt capture
    # (rpms-ops bin/capture.sh, PREFIX^NAME^VERSION lines) → { name => version }.
    # Without PACKAGES= the face stays {} exactly as before.
    packages = ENV["PACKAGES"] ? RpmsRpc::Conformance::PackageDump.parse_file(ENV["PACKAGES"]) : {}

    subset_note = nil
    if ENV["SUBSET"]
      allowlist = File.readlines(ENV["SUBSET"], chomp: true).map(&:strip).reject(&:empty?).to_set
      rpcs = rpcs.select { |name, _| allowlist.include?(name) }
      subset_note = "curated subset (#{rpcs.size} of #{total} RPCs in the dump)"
    end

    fingerprint = {
      "backend" => backend,
      "lineage" => { "iris_rpms" => "rpms", "yottadb_vista" => "vista", "worldvista" => "worldvista" }.fetch(backend, "rpms"),
      "release" => ENV["RELEASE"],
      "source" => {
        "kind" => "broker_dump",
        "captured_at" => captured_at,
        "dat_sha" => ENV["DAT_SHA"],
        "note" => [ ENV["NOTE"] || "file 8994 export (#{File.basename(dump_path)})", subset_note ].compact.join("; ")
      }.compact,
      "rpcs" => rpcs.sort.to_h,
      "packages" => packages,
      "patches" => [],
      "bmw_tables" => {}
    }

    header = +"# Fingerprint: #{env_name} — generated by `rake conformance:ingest`.\n"
    header << "# Source: file-8994 broker dump #{File.basename(dump_path)}, captured #{captured_at}.\n"
    if subset_note
      header << "# NOTE: #{subset_note} — representative, reviewable slice of the\n"
      header << "# real export; every line below is a real registry entry from the dump.\n"
    end
    if packages.empty?
      header << "# packages/patches/bmw_tables faces are empty until captured (follow-up).\n"
    else
      header << "# packages face: #{packages.size} PACKAGE #9.4 entries from #{File.basename(ENV["PACKAGES"])}.\n"
      header << "# patches/bmw_tables faces are empty until captured (follow-up).\n"
    end

    out_path = File.join(FINGERPRINTS_DIR, "#{env_name}.yml")
    FileUtils.mkdir_p(File.dirname(out_path))
    File.write(out_path, header + YAML.dump(fingerprint))
    puts "Wrote #{out_path} (#{rpcs.size} RPCs#{" of #{total} in dump" if subset_note}" \
         "#{", #{packages.size} packages" unless packages.empty?})"
  end

  desc "Classify TARGET= fingerprint against reference rungs; with REQUIRED=, " \
       "print the delta and fail if any required RPC is missing (CI gate)"
  task :probe do
    require "rpms_rpc/conformance"

    target_path = ENV["TARGET"] or abort "conformance:probe requires TARGET=<fingerprint.yml>"
    target = RpmsRpc::Conformance::FixtureReader.new(target_path).fingerprint

    references = Dir.glob(File.join(FINGERPRINTS_DIR, "references", "*.yml")).sort.map do |path|
      RpmsRpc::Conformance::FixtureReader.new(path).fingerprint
    end

    puts "Target: #{target_path} (#{target.rpc_names.size} RPCs, backend #{target.backend})"

    result = RpmsRpc::Conformance::Classifier.new(references: references).classify(target)
    puts "Classified as: #{result[:classified_as] || "(no references)"} " \
         "(coverage #{format("%.2f", result[:coverage])})"
    result[:ranked].each do |entry|
      line = "  #{entry[:release]}: coverage #{format("%.2f", entry[:coverage])}"
      line += ", package coverage #{format("%.2f", entry[:package_coverage])}" if entry[:package_coverage]
      puts line
    end

    if ENV["REQUIRED"]
      required = RpmsRpc::Conformance::FixtureReader.new(ENV["REQUIRED"]).fingerprint
      delta = RpmsRpc::Conformance::Delta.between(target: target, required: required)

      puts "Delta vs #{required.release || ENV["REQUIRED"]}: " \
           "#{delta[:missing].size} missing, #{delta[:extra].size} extra"
      delta[:missing].each { |rpc| puts "  missing: #{rpc}" }

      # PACKAGE #9.4 face — informational for now; the conformance gate
      # stays RPC-based until per-rung package references are authoritative.
      package_gaps = RpmsRpc::Conformance::Delta.package_gaps(target: target, required: required)
      unless package_gaps.empty?
        puts "Package gaps vs #{required.release || ENV["REQUIRED"]}: #{package_gaps.size}"
        package_gaps.each do |name, gap|
          puts "  package: #{name} requires #{gap[:required]}, target has #{gap[:actual] || "(absent)"}"
        end
      end

      abort "Target does not conform to #{required.release || ENV["REQUIRED"]}" unless delta[:missing].empty?
    end
  end
end
