# frozen_string_literal: true

# Wire-shape capture pipeline (docs/WIRE_CONTRACTS.md, issue #189).
#
#   rake wire:capture CONTAINER=rpms-ydb-9.0 RELEASE=bcer-9.0-ydb
#     [RUNTIME=docker] [BROKER_PORT=9100] [RPMS_ACCESS=] [RPMS_VERIFY=] [ONLY="RPC NAME"]
#
# `wire:capture` is the human/agent capture-side step (needs the live rung
# container — like conformance:ingest needs a broker dump); the contract
# test (test/rpms_rpc/wire_contract_test.rb) is the always-on CI gate and
# needs only the committed fixtures.
#
# Read-only discipline: the driver calls read RPCs with synthetic inputs
# against a rung WE OWN — never a customer instance, never a write RPC
# (write RPCs are routine-cited; the catalog enforces the split).
namespace :wire do
  FIXTURES_DIR = ENV["WIRE_FIXTURES_DIR"] ? File.expand_path(ENV["WIRE_FIXTURES_DIR"]) : File.expand_path("../../test/fixtures/wire_captures", __dir__)

  desc "Capture curated RPC wire returns from a live rung container into " \
       "test/fixtures/wire_captures/*.yml (CONTAINER=, RELEASE=; without " \
       "CONTAINER only routine-cite fixtures are rewritten)"
  task :capture do
    require "digest"
    require "fileutils"
    require "json"
    require "time"
    require "yaml"
    require "rpms_rpc/wire_capture"

    container = ENV["CONTAINER"]
    release = ENV["RELEASE"] || "bcer-9.0-ydb"
    runtime = ENV["RUNTIME"] || "docker"
    port = ENV["BROKER_PORT"] || "9100"
    acc = ENV["RPMS_ACCESS"] || "SYS123"
    ver = ENV["RPMS_VERIFY"] || "RPMS.000"
    only = ENV["ONLY"]
    # CITE_ONLY="RPC A,RPC B": write routine-cite fixtures for these
    # live-mode entries instead of calling them (e.g. the broker is down, or
    # a capture must land before the rung is reachable). The cite comes from
    # the catalog; no raw is claimed.
    cite_only = (ENV["CITE_ONLY"] || "").split(",").map(&:strip)
    captured_at = Time.now.utc.iso8601
    root = File.expand_path("../..", __dir__)

    captures = {}
    if container
      driver = File.join(root, "bin", "wire_capture_driver.rb")
      # Stage lib + driver as root (`docker cp` writes as root; chmod opens the
      # tree to a non-root exec user) — the rpms-ops evidence-script pattern.
      sh "#{runtime} exec -u root #{container} sh -lc 'rm -rf /tmp/rr /tmp/rr_driver.rb && mkdir -p /tmp/rr'"
      sh "#{runtime} cp #{root}/lib #{container}:/tmp/rr/lib"
      sh "#{runtime} cp #{driver} #{container}:/tmp/rr_driver.rb"
      sh "#{runtime} exec -u root #{container} sh -lc 'chmod -R a+rX /tmp/rr /tmp/rr_driver.rb'"

      json = `#{runtime} exec #{container} sh -lc "VISTA_RPC_ENV=development RPMS_RPC_LIB=/tmp/rr/lib BROKER_HOST=127.0.0.1 BROKER_PORT=#{port} RPMS_ACCESS=#{acc} RPMS_VERIFY=#{ver} ruby /tmp/rr_driver.rb"`
      abort "wire:capture driver failed:\n#{json}" unless $?.success?
      captures = JSON.parse(json).fetch("captures")
    else
      puts "No CONTAINER= given — writing routine-cite fixtures only."
    end

    FileUtils.mkdir_p(FIXTURES_DIR)
    written = 0
    RpmsRpc::WireCapture::CATALOG.each do |entry|
      next if only && entry.rpc != only

      if entry.live? && !cite_only.include?(entry.rpc)
        capture = captures[entry.rpc]
        next if capture.nil? # no container / not in this run: keep existing fixture

        if capture["error"]
          warn "SKIP #{entry.rpc}: #{capture["error"]} (existing fixture kept)"
          next
        end
        raw = capture.fetch("raw")
        data = fixture_data(entry, release, captured_at).merge(
          "source" => "live-capture",
          "inputs" => entry.inputs,
          "raw_return" => raw,
          "sha256" => Digest::SHA256.hexdigest(raw)
        )
      else
        data = fixture_data(entry, release, captured_at).merge("source" => "routine-cite")
      end

      # Round-trip through the validator so an invalid fixture can never be
      # written, only rejected here at authoring time.
      RpmsRpc::WireCapture::Fixture.new(data)

      path = File.join(FIXTURES_DIR, "#{entry.rpc.downcase.tr(" /", "--")}.yml")
      File.write(path, fixture_header(entry, data) + YAML.dump(data))
      puts "Wrote #{path} (#{data["source"]})"
      written += 1
    end
    puts "#{written} fixture(s) written to #{FIXTURES_DIR}"
  end

  def fixture_data(entry, release, captured_at)
    {
      "rpc" => entry.rpc,
      "mapping" => entry.mapping.to_s,
      "kind" => entry.kind,
      "release_tag" => release,
      "captured_at" => captured_at,
      "cite" => entry.cite,
      "note" => entry.note,
      "pieces" => entry.pieces.map do |p|
        piece = { "position" => p.position, "attributes" => p.attributes }
        piece["fileman_type"] = p.fileman_type if p.fileman_type
        piece
      end
    }.compact
  end

  def fixture_header(entry, data)
    header = +"# Wire capture: #{entry.rpc} — generated by `rake wire:capture` (issue #189).\n"
    header << if data["source"] == "live-capture"
                "# raw_return is VERBATIM from the #{data["release_tag"]} broker " \
                "(synthetic data only); do not hand-edit — re-run the capture.\n"
    else
      "# Routine-cited shape (no live call — see cite); do not hand-edit raw claims.\n"
    end
    header << "# Gated by test/rpms_rpc/wire_contract_test.rb against mapping :#{data["mapping"]}.\n"
  end
end
