# frozen_string_literal: true

require "minitest/autorun"
require "rpms_rpc/mock_client"
require "rpms_rpc/api/behavioral_health"

# Tests for RpmsRpc::BehavioralHealth — the AMHG (IHS Behavioral Health) RPC
# surface (rpms-rpc#227).
#
# Fixtures are hand-built from the M source the #8994 registry names, not
# round-tripped through our own formatter: a fixture generated by the code under
# test proves only that the code agrees with itself. Layouts below reproduce
# VISITL^AMHGD (AMHGD.m:10) and VI^AMHGDVF (AMHGDVF.m:9) line for line.
#
# Per ADR 0003 these fixtures are the *first* evidence, not the last: shipping
# still requires a captured real return per #189/#193. All data synthetic.
class BehavioralHealthTest < Minitest::Test
  BH = RpmsRpc::BehavioralHealth
  RS = "\x1e"  # $C(30) record separator
  US = "\x1f"  # $C(31) end of recordset

  # VISITL^AMHGD writes this header at AMHGD.m:17-18. Note it declares
  # EIGHTEEN columns — the trailing T00030DOBI is real in the header and
  # never appears in a data row (see AMHGD.m:53 vs :55).
  VISITS_HEADER =
    "T00010BMXIEN^T00030SortDate^T00030Date^T00050POV^T00020Axis V^T00020Clinic^" \
    "T00020Activity^T00020Visit Type^T00020Contact Type^T00030Provider^T00001Signed^" \
    "T00001EHR^T00001DeleteIntakes^T00030LocationofEncounter^T00001Group^T00080Program^" \
    "T00005ActivityTime^T00030DOBI#{RS}"

  # VI^AMHGDVF header, AMHGDVF.m:16.
  VISIT_INFO_HEADER =
    "T00010BMXIEN^T00030PrimaryProvider^T00030Program^T00030Clinic^T00030TypeofContact^" \
    "T00010ArrivalTime^T00020EncounterDate^T00030EncounterLocation^T00010ApptWi^" \
    "T00030CommofService^T00010Visit^T00001EHR#{RS}"

  def setup
    @mock = RpmsRpc.mock!
  end

  def teardown
    RpmsRpc.reset!
  end

  # -- AMHG GET VISITS -------------------------------------------------------

  # Seventeen fields, matching the row built at AMHGD.m:55.
  def visit_row(ien:, signed_marker:, ehr: "", group: "", pov: "DEPRESSIVE DISORDER")
    [ ien, "3250114", "JAN 14, 2025", pov, "3", "BH CLINIC", "INDIVIDUAL",
     "REGULAR", "AMBULATORY", "THERAPIST,EXAMPLE", signed_marker, ehr, "",
     "EXAMPLE HEALTH CENTER", group, "ADULT OUTPATIENT", "45" ].join("^") + RS
  end

  def seed_visits(*rows)
    @mock.seed_text(:amhg_visit_list, "3250101|3251231|100",
                    ([ VISITS_HEADER ] + rows + [ US ]).join("\n"))
  end

  def test_visits_parses_the_seventeen_field_row_and_skips_the_header
    seed_visits(visit_row(ien: "8801", signed_marker: ""))

    visits = BH.visits(100, from: "3250101", to: "3251231")

    assert_equal 1, visits.length, "header and $C(31) terminator are not records"
    v = visits.first
    assert_equal "8801", v[:ien]
    assert_equal "3250114", v[:visit_date]
    assert_equal "JAN 14, 2025", v[:display_date]
    assert_equal "DEPRESSIVE DISORDER", v[:pov]
    assert_equal "BH CLINIC", v[:clinic]
    assert_equal "THERAPIST,EXAMPLE", v[:provider]
    assert_equal "ADULT OUTPATIENT", v[:program]
  end

  # AMHGD.m:47 — AMHESIG is "*" when field 1112 is FALSE, i.e. the star means
  # NOT signed. A column named "Signed" whose marker means unsigned is a trap;
  # the API must expose the clinical fact, not the wire character.
  def test_signed_is_inverted_on_the_wire
    seed_visits(visit_row(ien: "8801", signed_marker: "*"),
                visit_row(ien: "8802", signed_marker: ""))

    unsigned, signed = BH.visits(100, from: "3250101", to: "3251231")

    refute unsigned[:signed], '"*" in the Signed column means NOT signed (AMHGD.m:47)'
    assert signed[:signed], "empty Signed column means the visit is signed"
  end

  # AMHGD.m:49 — when the EHR flag is set the star is cleared unconditionally,
  # so an EHR visit reports signed regardless of field 1112. That is the wire's
  # behaviour and we surface the EHR flag so a caller can tell the difference
  # rather than silently trusting `signed`.
  def test_ehr_visits_clear_the_unsigned_marker_and_expose_the_flag
    seed_visits(visit_row(ien: "8803", signed_marker: "", ehr: "1"))

    v = BH.visits(100, from: "3250101", to: "3251231").first

    assert v[:ehr], "EHR flag surfaced so callers can qualify :signed"
    assert v[:signed]
  end

  # AMHGD.m:53 computes AMHDOBI and AMHGD.m:55 never appends it. A consumer
  # trusting the 18-column header would wait for a field that never arrives.
  def test_dob_declared_in_the_header_is_never_emitted_so_is_not_invented
    seed_visits(visit_row(ien: "8801", signed_marker: ""))

    v = BH.visits(100, from: "3250101", to: "3251231").first

    refute v.key?(:dob), "header declares T00030DOBI but AMHGD.m:55 emits 17 fields"
  end

  # AMHGD.m:23-26 walks ^AMHREC("AE") over INVERSE dates, so rows arrive
  # newest-first. Callers paginating or taking .first depend on this.
  def test_rows_are_returned_in_wire_order_newest_first
    seed_visits(visit_row(ien: "8802", signed_marker: ""),
                visit_row(ien: "8801", signed_marker: ""))

    assert_equal %w[8802 8801], BH.visits(100, from: "3250101", to: "3251231").map { _1[:ien] }
  end

  def test_visits_sends_one_pipe_delimited_parameter
    seed_visits(visit_row(ien: "8801", signed_marker: ""))
    BH.visits(100, from: "3250101", to: "3251231")

    call = @mock.received_calls.find { |c| c[:rpc] == "AMHG GET VISITS" }
    assert_equal 1, call[:params].length,
                 "AMH rejects multi-actual calls with YDB-E-ACTLSTTOOLONG (#198)"
    assert_equal "3250101|3251231|100", call[:params].first
  end

  def test_visits_with_no_records_returns_empty
    @mock.seed_text(:amhg_visit_list, "3250101|3251231|100",
                    [ VISITS_HEADER, US ].join("\n"))

    assert_empty BH.visits(100, from: "3250101", to: "3251231")
  end

  # -- AMHG GET VISIT INFORMATION -------------------------------------------

  # Twelve fields, matching AMHGDVF.m:52. Five carry an IEN~external pair
  # (R="~" at AMHGDVF.m:12); Program and ApptWi are external-only even though
  # their internal variants are computed (AMHGDVF.m:27, :45).
  def seed_visit_info(arrival: "")
    row = [ "8801", "412~THERAPIST,EXAMPLE", "ADULT OUTPATIENT", "17~BH CLINIC",
           "3~AMBULATORY", arrival, "JAN 14, 2025", "55~EXAMPLE HEALTH CENTER",
           "SCHEDULED", "9~ON RESERVATION", "6612", "1" ].join("^") + RS
    @mock.seed_text(:amhg_visit_information, "8801",
                    [ VISIT_INFO_HEADER, row, US ].join("\n"))
  end

  def test_visit_information_splits_ien_name_pairs_on_the_tilde
    seed_visit_info

    info = BH.visit_information(8801)

    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, info[:primary_provider])
    assert_equal({ ien: "17", name: "BH CLINIC" }, info[:clinic])
    assert_equal({ ien: "3", name: "AMBULATORY" }, info[:type_of_contact])
    assert_equal({ ien: "55", name: "EXAMPLE HEALTH CENTER" }, info[:encounter_location])
    assert_equal({ ien: "9", name: "ON RESERVATION" }, info[:community_of_service])
  end

  # AMHGDVF.m:27 and :45 build AMHPRGS/AMHAPWIS and then emit the external
  # AMHPRG/AMHAPWI instead — these columns carry no IEN to split.
  def test_program_and_appointment_with_are_external_only
    seed_visit_info

    info = BH.visit_information(8801)

    assert_equal "ADULT OUTPATIENT", info[:program]
    assert_equal "SCHEDULED", info[:appointment_with]
  end

  # AMHGDVF.m:40 assigns AMHARR="" unconditionally, with the real computation
  # commented out on the same line. The column is permanently dead; reporting
  # nil is honest, reporting "" would look like a real empty value.
  def test_arrival_time_is_always_nil_because_the_wire_blanks_it
    seed_visit_info(arrival: "")

    assert_nil BH.visit_information(8801)[:arrival_time]
  end

  def test_visit_information_sends_one_pipe_delimited_parameter
    seed_visit_info
    BH.visit_information(8801)

    call = @mock.received_calls.find { |c| c[:rpc] == "AMHG GET VISIT INFORMATION" }
    assert_equal [ "8801" ], call[:params]
  end

  def test_visit_information_returns_nil_when_the_visit_has_no_row
    @mock.seed_text(:amhg_visit_information, "9999",
                    [ VISIT_INFO_HEADER, US ].join("\n"))

    assert_nil BH.visit_information(9999)
  end
end
