# frozen_string_literal: true

require "minitest/autorun"
require "rpms_rpc/mock_client"
require "rpms_rpc/api/behavioral_health"

# Tests for RpmsRpc::BehavioralHealth — the AMHG (IHS Behavioral Health) RPC
# surface (rpms-rpc#227).
#
# Fixtures are hand-built from the M source the #8994 registry names, not
# round-tripped through our own formatter: a fixture generated by the code under
# test proves only that the code agrees with itself. Layouts below reproduce
# VISITL^AMHGD (AMHGD.m:10) and VI^AMHGDVF (AMHGDVF.m:9) line for line.
#
# Per ADR 0003 these fixtures are the *first* evidence, not the last: shipping
# still requires a captured real return per #189/#193. All data synthetic.
class BehavioralHealthTest < Minitest::Test
  BH = RpmsRpc::BehavioralHealth
  RS = "\x1e"  # $C(30) record separator
  US = "\x1f"  # $C(31) end of recordset

  # VISITL^AMHGD writes this header at AMHGD.m:17-18. Note it declares
  # EIGHTEEN columns — the trailing T00030DOBI is real in the header and
  # never appears in a data row (see AMHGD.m:53 vs :55).
  VISITS_HEADER =
    "T00010BMXIEN^T00030SortDate^T00030Date^T00050POV^T00020Axis V^T00020Clinic^" \
    "T00020Activity^T00020Visit Type^T00020Contact Type^T00030Provider^T00001Signed^" \
    "T00001EHR^T00001DeleteIntakes^T00030LocationofEncounter^T00001Group^T00080Program^" \
    "T00005ActivityTime^T00030DOBI#{RS}"

  # VI^AMHGDVF header, AMHGDVF.m:16.
  VISIT_INFO_HEADER =
    "T00010BMXIEN^T00030PrimaryProvider^T00030Program^T00030Clinic^T00030TypeofContact^" \
    "T00010ArrivalTime^T00020EncounterDate^T00030EncounterLocation^T00010ApptWi^" \
    "T00030CommofService^T00010Visit^T00001EHR#{RS}"

  def setup
    @mock = RpmsRpc.mock!
  end

  def teardown
    RpmsRpc.reset!
  end

  # -- AMHG GET VISITS -------------------------------------------------------

  # Seventeen fields, matching the row built at AMHGD.m:55.
  def visit_row(ien:, signed_marker:, ehr: "", group: "", pov: "DEPRESSIVE DISORDER")
    [ ien, "3250114", "JAN 14, 2025", pov, "3", "BH CLINIC", "INDIVIDUAL",
     "REGULAR", "AMBULATORY", "THERAPIST,EXAMPLE", signed_marker, ehr, "",
     "EXAMPLE HEALTH CENTER", group, "ADULT OUTPATIENT", "45" ].join("^") + RS
  end

  def seed_visits(*rows)
    @mock.seed_text(:amhg_visit_list, "3250101|3251231|100",
                    ([ VISITS_HEADER ] + rows + [ US ]).join("\n"))
  end

  def test_visits_parses_the_seventeen_field_row_and_skips_the_header
    seed_visits(visit_row(ien: "8801", signed_marker: ""))

    visits = BH.visits(100, from: "3250101", to: "3251231")

    assert_equal 1, visits.length, "header and $C(31) terminator are not records"
    v = visits.first
    assert_equal "8801", v[:ien]
    assert_equal "3250114", v[:visit_date]
    assert_equal "JAN 14, 2025", v[:display_date]
    assert_equal "DEPRESSIVE DISORDER", v[:pov]
    assert_equal "BH CLINIC", v[:clinic]
    assert_equal "THERAPIST,EXAMPLE", v[:provider]
    assert_equal "ADULT OUTPATIENT", v[:program]
  end

  # AMHGD.m:47 — AMHESIG is "*" when field 1112 is FALSE, i.e. the star means
  # NOT signed. A column named "Signed" whose marker means unsigned is a trap;
  # the API must expose the clinical fact, not the wire character.
  def test_signed_is_inverted_on_the_wire
    seed_visits(visit_row(ien: "8801", signed_marker: "*"),
                visit_row(ien: "8802", signed_marker: ""))

    unsigned, signed = BH.visits(100, from: "3250101", to: "3251231")

    refute unsigned[:signed], '"*" in the Signed column means NOT signed (AMHGD.m:47)'
    assert signed[:signed], "empty Signed column means the visit is signed"
  end

  # AMHGD.m:49 — when the EHR flag is set the star is cleared unconditionally,
  # so an EHR visit reports signed regardless of field 1112. That is the wire's
  # behaviour and we surface the EHR flag so a caller can tell the difference
  # rather than silently trusting `signed`.
  def test_ehr_visits_clear_the_unsigned_marker_and_expose_the_flag
    seed_visits(visit_row(ien: "8803", signed_marker: "", ehr: "1"))

    v = BH.visits(100, from: "3250101", to: "3251231").first

    assert v[:ehr], "EHR flag surfaced so callers can qualify :signed"
    assert v[:signed]
  end

  # AMHGD.m:53 computes AMHDOBI and AMHGD.m:55 never appends it. A consumer
  # trusting the 18-column header would wait for a field that never arrives.
  def test_dob_declared_in_the_header_is_never_emitted_so_is_not_invented
    seed_visits(visit_row(ien: "8801", signed_marker: ""))

    v = BH.visits(100, from: "3250101", to: "3251231").first

    refute v.key?(:dob), "header declares T00030DOBI but AMHGD.m:55 emits 17 fields"
  end

  # AMHGD.m:23-26 walks ^AMHREC("AE") over INVERSE dates, so rows arrive
  # newest-first. Callers paginating or taking .first depend on this.
  def test_rows_are_returned_in_wire_order_newest_first
    seed_visits(visit_row(ien: "8802", signed_marker: ""),
                visit_row(ien: "8801", signed_marker: ""))

    assert_equal %w[8802 8801], BH.visits(100, from: "3250101", to: "3251231").map { _1[:ien] }
  end

  def test_visits_sends_one_pipe_delimited_parameter
    seed_visits(visit_row(ien: "8801", signed_marker: ""))
    BH.visits(100, from: "3250101", to: "3251231")

    call = @mock.received_calls.find { |c| c[:rpc] == "AMHG GET VISITS" }
    assert_equal 1, call[:params].length,
                 "AMH rejects multi-actual calls with YDB-E-ACTLSTTOOLONG (#198)"
    assert_equal "3250101|3251231|100", call[:params].first
  end

  def test_visits_with_no_records_returns_empty
    @mock.seed_text(:amhg_visit_list, "3250101|3251231|100",
                    [ VISITS_HEADER, US ].join("\n"))

    assert_empty BH.visits(100, from: "3250101", to: "3251231")
  end

  # -- AMHG GET VISIT INFORMATION -------------------------------------------

  # Twelve fields, matching AMHGDVF.m:52. Five carry an IEN~external pair
  # (R="~" at AMHGDVF.m:12); Program and ApptWi are external-only even though
  # their internal variants are computed (AMHGDVF.m:27, :45).
  def seed_visit_info(arrival: "")
    row = [ "8801", "412~THERAPIST,EXAMPLE", "ADULT OUTPATIENT", "17~BH CLINIC",
           "3~AMBULATORY", arrival, "JAN 14, 2025", "55~EXAMPLE HEALTH CENTER",
           "SCHEDULED", "9~ON RESERVATION", "6612", "1" ].join("^") + RS
    @mock.seed_text(:amhg_visit_information, "8801",
                    [ VISIT_INFO_HEADER, row, US ].join("\n"))
  end

  def test_visit_information_splits_ien_name_pairs_on_the_tilde
    seed_visit_info

    info = BH.visit_information(8801)

    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, info[:primary_provider])
    assert_equal({ ien: "17", name: "BH CLINIC" }, info[:clinic])
    assert_equal({ ien: "3", name: "AMBULATORY" }, info[:type_of_contact])
    assert_equal({ ien: "55", name: "EXAMPLE HEALTH CENTER" }, info[:encounter_location])
    assert_equal({ ien: "9", name: "ON RESERVATION" }, info[:community_of_service])
  end

  # AMHGDVF.m:27 and :45 build AMHPRGS/AMHAPWIS and then emit the external
  # AMHPRG/AMHAPWI instead — these columns carry no IEN to split.
  def test_program_and_appointment_with_are_external_only
    seed_visit_info

    info = BH.visit_information(8801)

    assert_equal "ADULT OUTPATIENT", info[:program]
    assert_equal "SCHEDULED", info[:appointment_with]
  end

  # AMHGDVF.m:40 assigns AMHARR="" unconditionally, with the real computation
  # commented out on the same line. The column is permanently dead; reporting
  # nil is honest, reporting "" would look like a real empty value.
  def test_arrival_time_is_always_nil_because_the_wire_blanks_it
    seed_visit_info(arrival: "")

    assert_nil BH.visit_information(8801)[:arrival_time]
  end

  def test_visit_information_sends_one_pipe_delimited_parameter
    seed_visit_info
    BH.visit_information(8801)

    call = @mock.received_calls.find { |c| c[:rpc] == "AMHG GET VISIT INFORMATION" }
    assert_equal [ "8801" ], call[:params]
  end

  def test_visit_information_returns_nil_when_the_visit_has_no_row
    @mock.seed_text(:amhg_visit_information, "9999",
                    [ VISIT_INFO_HEADER, US ].join("\n"))

    assert_nil BH.visit_information(9999)
  end
  # -- visit detail tabs -----------------------------------------------------

  def seed_tab(mapping, header, *rows)
    @mock.seed_text(mapping, "8801", ([ header + RS ] + rows.map { |r| r + RS } + [ US ]).join("\n"))
  end

  # ACT^AMHGDVF (AMHGDVF.m:291) — one row, two IEN~name pairs.
  def test_visit_activity_splits_pairs_and_reports_a_blank_interpreter_flag_as_false
    seed_tab(:amhg_visit_activity,
             "T00010BMXIEN^T00030ActivityType^T00010ActivityTime^T00010Flag^" \
             "T00030LocalServiceSite^T00010NumberServed^T00001InterpreterUtilized",
             "8801^12~INDIVIDUAL THERAPY^45^^7~EXAMPLE CLINIC SITE^1^")

    act = BH.visit_activity(8801)

    assert_equal({ ien: "12", name: "INDIVIDUAL THERAPY" }, act[:activity_type])
    assert_equal({ ien: "7", name: "EXAMPLE CLINIC SITE" }, act[:local_service_site])
    assert_equal "45", act[:activity_time]
    refute act[:interpreter_utilized], "AMHGDVF.m:311 blanks the flag when falsy"
  end

  # AMHGDVF.m:67 — the column called BMXIEN is field .01's INTERNAL value, a
  # pointer to the POV code file, not the subfile IEN. Naming it :code_pointer
  # keeps a caller from using it as a record address.
  def test_axis_ii_first_column_is_a_code_pointer_not_a_record_ien
    seed_tab(:amhg_visit_axis_ii, "T00010BMXIEN^T00010Code^T00100Narrative",
             "441^F32.9^MAJOR DEPRESSIVE DISORDER, UNSPECIFIED",
             "512^F41.1^GENERALIZED ANXIETY DISORDER")

    povs = BH.visit_axis_ii(8801)

    assert_equal 2, povs.length
    assert_equal "441", povs.first[:code_pointer]
    refute povs.first.key?(:ien), "the subfile IEN is never emitted (AMHGDVF.m:64)"
    assert_equal "F32.9", povs.first[:code]
  end

  def test_axis_iv_has_the_same_pointer_shape
    seed_tab(:amhg_visit_axis_iv, "T00010BMXIEN^T00010Code^T00100Narrative",
             "88^ECON^ECONOMIC PROBLEMS")

    assert_equal "88", BH.visit_axis_iv(8801).first[:code_pointer]
  end

  # AXIS3 is free text, one column, many rows. A caret cannot appear: the wire
  # translates it to a space (AMHGDVF.m:88).
  def test_axis_iii_returns_raw_lines
    seed_tab(:amhg_visit_axis_iii, "T00250AxisIII",
             "HYPERTENSION, WELL CONTROLLED", "TYPE 2 DIABETES")

    assert_equal [ "HYPERTENSION, WELL CONTROLLED", "TYPE 2 DIABETES" ], BH.visit_axis_iii(8801)
  end

  # AXIS5 always emits exactly one row — there is no loop (AMHGDVF.m:123).
  def test_axis_v_returns_one_row_even_when_empty
    seed_tab(:amhg_visit_axis_v, "T00010AxisV^T00020GAF", "^")

    assert_equal({ axis_v: nil, gaf: nil }, BH.visit_axis_v(8801))
  end

  def test_axis_v_carries_the_gaf_score
    seed_tab(:amhg_visit_axis_v, "T00010AxisV^T00020GAF", "55^55 - MODERATE SYMPTOMS")

    assert_equal({ axis_v: "55", gaf: "55 - MODERATE SYMPTOMS" }, BH.visit_axis_v(8801))
  end

  # AMHGDVF.m:140 sends the raw node with NO caret sanitisation, so a chief
  # complaint containing "^" must survive as one string.
  def test_chief_complaint_keeps_carets_instead_of_splitting_into_columns
    seed_tab(:amhg_visit_chief_complaint, "T00100ChiefComplaint",
             "PATIENT REPORTS LOW MOOD ^ POOR SLEEP")

    assert_equal "PATIENT REPORTS LOW MOOD ^ POOR SLEEP", BH.visit_chief_complaint(8801)
  end

  def test_chief_complaint_is_nil_when_the_single_row_is_blank
    seed_tab(:amhg_visit_chief_complaint, "T00100ChiefComplaint", "")

    assert_nil BH.visit_chief_complaint(8801)
  end

  def test_soap_returns_raw_lines_regardless_of_source
    seed_tab(:amhg_visit_soap, "T00250Soap",
             "S: Patient reports improved sleep.", "O: Affect brighter.")

    assert_equal [ "S: Patient reports improved sleep.", "O: Affect brighter." ], BH.visit_soap(8801)
  end

  def test_comment_appointment_returns_raw_lines
    seed_tab(:amhg_visit_comment_appointment, "T00250CommentAppointment",
             "Next appointment in two weeks.")

    assert_equal [ "Next appointment in two weeks." ], BH.visit_comment_appointment(8801)
  end

  # AMHGDINT.m:114 walks ^AMHRINTK(ien,41) — the parameter is an INTAKE IEN
  # despite the RPC being named GET VISIT ASSESSMENT.
  def test_assessment_is_keyed_by_intake_ien
    @mock.seed_text(:amhg_visit_assessment, "5501",
                    [ "T00250Assessment" + RS, "Client engaged, motivated." + RS, US ].join("\n"))

    assert_equal [ "Client engaged, motivated." ], BH.visit_assessment(intake_ien: 5501)

    call = @mock.received_calls.find { |c| c[:rpc] == "AMHG GET VISIT ASSESSMENT" }
    assert_equal [ "5501" ], call[:params]
  end

  # AMHGDVF3.m:157 increments AMHI once BEFORE the F I= loop at :161, so every
  # matching screening overwrites the previous one at the same subscript. The
  # wire can only ever carry one. We surface what arrives and say so; we do
  # not pretend the list is complete.
  def test_screening_returns_at_most_one_row_because_the_wire_overwrites
    seed_tab(:amhg_visit_screening,
             "T00010BMXIEN^T00030ScreeningType^T00030ScreeningResult^" \
             "T00010ScreeningProviderIEN^T00030ScreeningProvider^T00250ScreeningComment",
             "8801^Suicide Risk^NEGATIVE^412^THERAPIST,EXAMPLE^No current ideation")

    screenings = BH.visit_screenings(8801)

    assert_equal 1, screenings.length
    s = screenings.first
    assert_equal "Suicide Risk", s[:screening_type]
    assert_equal "NEGATIVE", s[:result]
    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, s[:provider])
    assert_equal "8801", s[:visit_ien], "BMXIEN is the visit IEN repeated, not a screening id"
  end

  def test_screening_is_empty_when_no_screening_has_a_result
    seed_tab(:amhg_visit_screening,
             "T00010BMXIEN^T00030ScreeningType^T00030ScreeningResult^" \
             "T00010ScreeningProviderIEN^T00030ScreeningProvider^T00250ScreeningComment")

    assert_empty BH.visit_screenings(8801)
  end
  # -- treatment plans -------------------------------------------------------

  TPL_HEADER = "T00010BMXIEN^T00030SortDate^T00030DateEstablished^T00030Program^T00030Status^" \
               "T00080Problem^T00030Provider^T00030ReviewDate^T00010Reviews^T00030ClosedDate"

  TP_HEADER = "T00010BMXIEN^T00030DateEstablished^T00030Program^T00030TargetDate^T00030ReviewDate^" \
              "T00030DateClosed^T00030DesignatedProvider^T00240ProblemList^T00030CaseAdmit^" \
              "T00030ConcurredDate^T00030ConcurSupervisor^T00001dsm4"

  REV_HEADER = "T00010BMXIEN^T00010BMXIEN2^T00030ReviewDate^T00030ReviewProvider^" \
               "T00030ReviewSupervisor^T00030NextReviewDate^T00050ReviewProviderComplete^" \
               "T00050ReviewSupervisorComplete"

  def test_treatment_plans_parses_the_ten_field_row
    @mock.seed_text(:amhg_treatment_plan_list, "3250101|3251231|100",
                    [ TPL_HEADER + RS,
                      "77^3250110^JAN 10, 2025^ADULT OUTPATIENT^ACTIVE^MAJOR DEPRESSIVE DISORDER^" \
                      "THERAPIST,EXAMPLE^MAR 10, 2025^2^" + RS,
                      US ].join("\n"))

    plans = BH.treatment_plans(100, from: "3250101", to: "3251231")

    assert_equal 1, plans.length
    p = plans.first
    assert_equal "77", p[:ien]
    assert_equal "ACTIVE", p[:status]
    assert_equal "MAJOR DEPRESSIVE DISORDER", p[:problem]
    assert_equal "2", p[:review_count]
    assert_nil p[:closed_date], "an open plan carries no closed date"
  end

  # AMHGD.m:186 formats ReviewDate through $$LVDT, while TP^AMHGDTP emits the
  # SAME field as a raw internal FileMan date (AMHGDTP.m:24). A caller moving
  # from list to detail sees two formats for one field; both are surfaced as
  # they arrive rather than silently normalised.
  def test_list_and_detail_disagree_on_date_format_and_we_do_not_hide_it
    @mock.seed_text(:amhg_treatment_plan_list, "3250101|3251231|100",
                    [ TPL_HEADER + RS,
                      "77^3250110^JAN 10, 2025^ADULT OUTPATIENT^ACTIVE^DEPRESSION^" \
                      "THERAPIST,EXAMPLE^MAR 10, 2025^2^" + RS, US ].join("\n"))
    @mock.seed_text(:amhg_treatment_plan, "77",
                    [ TP_HEADER + RS,
                      "77^3250110^ADULT OUTPATIENT^3250401^3250310^^412~THERAPIST,EXAMPLE^" \
                      "DEPRESSION^3250110^3250115^509~SUPERVISOR,EXAMPLE^1" + RS, US ].join("\n"))

    listed = BH.treatment_plans(100, from: "3250101", to: "3251231").first
    detail = BH.treatment_plan(77)

    assert_equal "MAR 10, 2025", listed[:review_date], "list is $$LVDT-formatted (AMHGD.m:186)"
    assert_equal "3250310", detail[:review_date], "detail is internal FileMan (AMHGDTP.m:24)"
  end

  # AMHGDTP.m:29 builds AMHPRGS as an IEN~name pair and AMHGDTP.m:44 emits the
  # external AMHPRG instead — Program carries no IEN. DesignatedProvider and
  # ConcurSupervisor do (AMHGDTP.m:32, :37).
  def test_treatment_plan_pairs_only_where_the_wire_sends_them
    @mock.seed_text(:amhg_treatment_plan, "77",
                    [ TP_HEADER + RS,
                      "77^3250110^ADULT OUTPATIENT^3250401^3250310^^412~THERAPIST,EXAMPLE^" \
                      "DEPRESSION^3250110^3250115^509~SUPERVISOR,EXAMPLE^1" + RS, US ].join("\n"))

    tp = BH.treatment_plan(77)

    assert_equal "ADULT OUTPATIENT", tp[:program], "external only — AMHGDTP.m:44"
    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, tp[:designated_provider])
    assert_equal({ ien: "509", name: "SUPERVISOR,EXAMPLE" }, tp[:concur_supervisor])
    assert tp[:dsm4]
  end

  def test_treatment_plan_is_nil_when_the_ien_yields_no_row
    @mock.seed_text(:amhg_treatment_plan, "999", [ TP_HEADER + RS, US ].join("\n"))

    assert_nil BH.treatment_plan(999)
  end

  # AMHGDTP.m:197 — BMXIEN is the PLAN ien repeated; BMXIEN2 is the review
  # subfile ien (AMHDA), the only addressable identifier on the row.
  def test_reviews_expose_the_addressable_subfile_ien
    seed_reviews

    review = BH.treatment_plan_reviews(77).first

    assert_equal "77", review[:plan_ien]
    assert_equal "3", review[:ien], "BMXIEN2 is the review subfile IEN (AMHGDTP.m:197)"
  end

  # The columns named ReviewProviderComplete / ReviewSupervisorComplete do NOT
  # carry completion status — AMHGDTP.m:193-194 build them as IEN~name pairs.
  # A caller reading them as booleans would treat every named reviewer as
  # "complete".
  def test_review_complete_columns_are_ien_name_pairs_not_completion_flags
    seed_reviews

    review = BH.treatment_plan_reviews(77).first

    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, review[:review_provider])
    assert_equal({ ien: "509", name: "SUPERVISOR,EXAMPLE" }, review[:review_supervisor])
    refute review.key?(:review_provider_complete),
           "the wire's *Complete columns are identity, not status"
  end

  def seed_reviews
    @mock.seed_text(:amhg_treatment_plan_reviews, "77",
                    [ REV_HEADER + RS,
                      "77^3^MAR 10, 2025^THERAPIST,EXAMPLE^SUPERVISOR,EXAMPLE^JUN 10, 2025^" \
                      "412~THERAPIST,EXAMPLE^509~SUPERVISOR,EXAMPLE" + RS, US ].join("\n"))
  end

  # AMHGDTP.m:215 emits the PLAN ien and never AMHDA, so a participant row
  # carries no identifier of its own and cannot be addressed for edit.
  def test_participants_are_not_individually_addressable
    @mock.seed_text(:amhg_treatment_plan_participants, "77",
                    [ "T00010BMXIEN^T00030Participant^T00030Relationship" + RS,
                      "77^DOE,EXAMPLE^SPOUSE" + RS, US ].join("\n"))

    participant = BH.treatment_plan_participants(77).first

    assert_equal "DOE,EXAMPLE", participant[:participant]
    assert_equal "SPOUSE", participant[:relationship]
    refute participant.key?(:ien), "the subfile IEN is never emitted (AMHGDTP.m:215)"
  end

  # AMHGDTP.m:168 sends raw nodes with no caret sanitisation.
  def test_narrative_returns_raw_lines_keeping_carets
    @mock.seed_text(:amhg_treatment_plan_narrative, "77",
                    [ "T00250TreatmentPlanNarrative" + RS,
                      "Goal 1: reduce PHQ-9 ^ improve sleep" + RS, US ].join("\n"))

    assert_equal [ "Goal 1: reduce PHQ-9 ^ improve sleep" ], BH.treatment_plan_narrative(77)
  end
  # -- suicide risk ----------------------------------------------------------

  SFL_HEADER = "T00010BMXIEN^T00030SortDate^T00030Date^T00030LocalCaseNumber^T00030Provider^" \
               "T00080SuicidalBehavior^T00001Incomplete"

  # SIXTEEN columns. The routine builds this across TWO SET statements
  # (AMHGDSF.m:19-20); anything reading only the first sees eleven.
  SF_HEADER = "T00010BMXIEN^T00030LocalCaseNumber^T00050Provider^T00030DateofAct^" \
              "T00050CommunityWhereOccurred^T00010RelationshipStatus^T00010EmploymentStatus^" \
              "T00010Education^T00010HighestGrade^T00010SuicidalBehavior^T00010PreviousAttempts^" \
              "T00010Lethality^T00010LocationofAct^T00080LocationOther^T00050Disposition^" \
              "T00080DispositionText"

  # AMHGD.m:256 — "I" marks the form INCOMPLETE, empty marks it complete.
  def test_suicide_forms_reports_completeness_from_the_incomplete_marker
    @mock.seed_text(:amhg_suicide_form_list, "3250101|3251231|100",
                    [ SFL_HEADER + RS,
                      "31^3250114^JAN 14, 2025^LC-1001^THERAPIST,EXAMPLE^ATTEMPT^I" + RS,
                      "32^3250102^JAN 02, 2025^LC-1002^THERAPIST,EXAMPLE^IDEATION^" + RS,
                      US ].join("\n"))

    incomplete, complete = BH.suicide_forms(100, from: "3250101", to: "3251231")

    refute incomplete[:complete], '"I" marks the form incomplete (AMHGD.m:256)'
    assert complete[:complete]
    assert_equal "LC-1001", incomplete[:local_case_number]
  end

  def test_suicide_form_parses_all_sixteen_columns_not_the_eleven_a_single_set_would_show
    seed_suicide_form

    form = BH.suicide_form(31)

    assert_equal "31", form[:ien]
    assert_equal "LC-1001", form[:local_case_number]
    assert_equal "3250114", form[:date_of_act], "internal FileMan (AMHGDSF.m:24)"
    assert_equal "HIGH", form[:lethality], "column 12 — only reachable if all 16 are parsed"
    assert_equal "HOSPITALIZED", form[:disposition][:name]
    assert_equal "Transferred to inpatient unit", form[:disposition_text]
  end

  # AMHGDSF.m:22, :27, :43 — provider, community and disposition are IEN~name
  # pairs; the rest are plain external values.
  def test_suicide_form_pairs_only_the_three_pointer_columns
    seed_suicide_form

    form = BH.suicide_form(31)

    assert_equal({ ien: "412", name: "THERAPIST,EXAMPLE" }, form[:provider])
    assert_equal({ ien: "88", name: "EXAMPLE COMMUNITY" }, form[:community_where_occurred])
    assert_equal({ ien: "4", name: "HOSPITALIZED" }, form[:disposition])
    assert_equal "SINGLE", form[:relationship_status]
  end

  def seed_suicide_form
    row = [ "31", "LC-1001", "412~THERAPIST,EXAMPLE", "3250114", "88~EXAMPLE COMMUNITY",
            "SINGLE", "UNEMPLOYED", "HIGH SCHOOL", "12", "ATTEMPT", "1", "HIGH",
            "HOME", "", "4~HOSPITALIZED", "Transferred to inpatient unit" ].join("^") + RS
    @mock.seed_text(:amhg_suicide_form, "31", [ SF_HEADER + RS, row, US ].join("\n"))
  end

  METH_HEADER = "T00010BMXIEN^T00010Method^T00050MethodIfOther^T00050DrugIfOverdose^T00050DrugIfOther"

  # AMHGDSF.m:73 — method 7 with recorded drugs emits ONE ROW PER DRUG, so a
  # single method can appear many times. AMHDA (the method subfile IEN) is
  # never emitted, so the rows carry no way to group or address them.
  def test_overdose_method_emits_one_row_per_drug_and_no_method_identifier
    @mock.seed_text(:amhg_suicide_form_methods, "31",
                    [ METH_HEADER + RS,
                      "31^7^^101~ACETAMINOPHEN^" + RS,
                      "31^7^^102~IBUPROFEN^" + RS,
                      US ].join("\n"))

    methods = BH.suicide_form_methods(31)

    assert_equal 2, methods.length
    assert_equal %w[7 7], methods.map { _1[:method] }
    assert_equal "ACETAMINOPHEN", methods.first[:drug][:name]
    refute methods.first.key?(:ien), "the method subfile IEN is never emitted (AMHGDSF.m:73)"
  end

  # AMHGDSF.m:75-78 — a non-overdose method still emits a row, with the drug
  # columns blank.
  def test_non_overdose_method_emits_one_row_with_no_drug
    @mock.seed_text(:amhg_suicide_form_methods, "31",
                    [ METH_HEADER + RS, "31^3^^^" + RS, US ].join("\n"))

    method = BH.suicide_form_methods(31).first

    assert_equal "3", method[:method]
    assert_nil method[:drug]
  end

  # AMHGDSF.m:106-108 — when field .26 is not "2" the routine still emits one
  # row carrying the substance value with blank drug columns, so an empty
  # result never means "not asked".
  def test_substances_always_emit_at_least_one_row
    @mock.seed_text(:amhg_suicide_form_substances, "31",
                    [ "T00010BMXIEN^T00010Substance^T00050Drug^T00050DrugIfOther" + RS,
                      "31^1^^" + RS, US ].join("\n"))

    substances = BH.suicide_form_substances(31)

    assert_equal 1, substances.length
    assert_equal "1", substances.first[:substance]
    assert_nil substances.first[:drug]
  end

  def test_substances_pair_the_drug_when_one_is_recorded
    @mock.seed_text(:amhg_suicide_form_substances, "31",
                    [ "T00010BMXIEN^T00010Substance^T00050Drug^T00050DrugIfOther" + RS,
                      "31^2^77~ALCOHOL^" + RS, US ].join("\n"))

    assert_equal({ ien: "77", name: "ALCOHOL" }, BH.suicide_form_substances(31).first[:drug])
  end

  def test_contributing_factors_are_a_plain_multi_row_list
    @mock.seed_text(:amhg_suicide_form_contributing_factors, "31",
                    [ "T00010BMXIEN^T00010ContributingFactor^T00050ContributingFactorIfOther" + RS,
                      "31^4^" + RS, "31^99^Recent bereavement" + RS, US ].join("\n"))

    factors = BH.suicide_form_contributing_factors(31)

    assert_equal 2, factors.length
    assert_equal "Recent bereavement", factors.last[:if_other]
  end
end
