# frozen_string_literal: true

require "minitest/autorun"
require "tmpdir"
require "yaml"
require "rpms_rpc/conformance/reader"

class RpmsRpc::Conformance::ReaderTest < Minitest::Test
  def test_base_reader_fingerprint_is_abstract
    assert_raises(NotImplementedError) do
      RpmsRpc::Conformance::Reader.new.fingerprint
    end
  end

  def test_fixture_reader_loads_a_committed_yaml_into_a_fingerprint
    Dir.mktmpdir do |dir|
      path = File.join(dir, "target.yml")
      File.write(path, YAML.dump(
                         "backend" => "iris_rpms",
                         "lineage" => "rpms",
                         "rpcs" => { "ORWPT SELECT" => { "tag" => "SELECT", "routine" => "ORWPT" } }
                       ))

      fp = RpmsRpc::Conformance::FixtureReader.new(path).fingerprint

      assert_instance_of RpmsRpc::Conformance::Fingerprint, fp
      assert_equal "iris_rpms", fp.backend
      assert_equal Set["ORWPT SELECT"], fp.rpc_names
    end
  end

  # conformance:probe ranks a target against every reference under
  # references/; a hand-authored placeholder must not be one of the rungs.
  def test_reference_paths_skip_files_whose_first_line_says_placeholder
    Dir.mktmpdir do |dir|
      placeholder = File.join(dir, "bcer-1.0.yml")
      File.write(placeholder, "# SEED reference fingerprint for the bcer-1.0 rung — HAND-AUTHORED PLACEHOLDER.\nrpcs: {}\n")
      captured = File.join(dir, "bcer-2.0.yml")
      File.write(captured, "# Fingerprint: references/bcer-2.0 — generated by `rake conformance:ingest`.\nrpcs: {}\n")
      # The mark counts only on the first line: a capture may mention the word later.
      mentions = File.join(dir, "bcer-3.0.yml")
      File.write(mentions, "# Fingerprint: references/bcer-3.0\n# replaces the PLACEHOLDER of the same rung\nrpcs: {}\n")
      File.write(File.join(dir, "notes.txt"), "PLACEHOLDER\n")

      assert RpmsRpc::Conformance::FixtureReader.placeholder?(placeholder)
      refute RpmsRpc::Conformance::FixtureReader.placeholder?(captured)
      refute RpmsRpc::Conformance::FixtureReader.placeholder?(mentions)
      assert_equal [ captured, mentions ], RpmsRpc::Conformance::FixtureReader.reference_paths(dir)
    end
  end

  # The two committed seeds are placeholders by their own first line, and the
  # pinned reference is not; the probe ranks against the pinned one alone.
  def test_committed_placeholder_references_are_not_ranked
    dir = File.expand_path("../../../data/fingerprints/references", __dir__)
    ranked = RpmsRpc::Conformance::FixtureReader.reference_paths(dir).map { |p| File.basename(p) }

    refute_includes ranked, "bcer-5.0.yml"
    refute_includes ranked, "bcer-8.0.yml"
    refute_empty ranked, "no pinned reference under data/fingerprints/references"
    ranked.each { |name| assert_match(/\Abcer-\d+\.\d+-\d{8}-[0-9a-f]+-(ydb|iris)\.yml\z/, name) }
  end

  def test_broker_reader_is_a_documented_stub
    error = assert_raises(NotImplementedError) do
      RpmsRpc::Conformance::BrokerReader.new(client: :some_client).fingerprint
    end
    assert_match(/follow-up: live capture/, error.message)
  end

  def test_iris_sql_reader_is_a_documented_stub
    error = assert_raises(NotImplementedError) do
      RpmsRpc::Conformance::IrisSqlReader.new(connection: :some_connection).fingerprint
    end
    assert_match(/follow-up: live capture/, error.message)
  end
end
