# frozen_string_literal: true

require "date"
require "fileutils"
require "yaml"
require "rpms_rpc/conformance/package_dump"

module RpmsRpc
  module Conformance
    # Turn a file-8994 broker dump (+ optional #9.4 packages dump) into a committed fingerprint
    # YAML. Extracted from the conformance:ingest rake task so `conformance:pin` can run the
    # identical transformation over a verified rpms-ops inventory and stamp its provenance
    # (the source.inventory face) into the result.
    module Ingest
      LINEAGE = {
        "iris_rpms" => "rpms",
        "yottadb_rpms" => "rpms",
        "yottadb_vista" => "vista",
        "worldvista" => "worldvista"
      }.freeze
      BACKEND_FOR_ENGINE = { "iris" => "iris_rpms", "yottadb" => "yottadb_rpms" }.freeze

      # Dump lines are #8994 0-nodes, the fields ^DD(8994) defines in order:
      #   .01 NAME ^ .02 TAG ^ .03 ROUTINE ^ .04 RETURN VALUE TYPE (1-5) ^ .05 AVAILABILITY (P/S/A/R)
      #   ^ .06 INACTIVE (0-3) ^ ...
      # A name with no entry point keeps tag/routine nil. Returns [rpcs_hash, total_lines].
      def self.parse_dump(path)
        total = 0
        rpcs = {}
        File.foreach(path) do |line|
          line = line.chomp
          next if line.empty?

          total += 1
          name, tag, routine, return_type, availability, inactive = line.split("^")
          meta = { "tag" => tag, "routine" => routine }
          meta["return_type"] = return_type unless return_type.to_s.empty?
          meta["availability"] = availability unless availability.to_s.empty?
          meta["inactive"] = inactive unless inactive.to_s.empty? || inactive == "0"
          rpcs[name] = meta
        end
        [ rpcs, total ]
      end

      # Write data/fingerprints/<env>.yml. Returns { path:, rpcs:, total:, packages: }.
      def self.run(dump:, env:, fingerprints_dir:, backend: "iris_rpms", captured_at: Date.today.iso8601,
                   packages: nil, subset: nil, release: nil, dat_sha: nil, note: nil, inventory: nil)
        rpcs, total = parse_dump(dump)
        package_versions = packages ? PackageDump.parse_file(packages) : {}

        subset_note = nil
        if subset
          allowlist = File.readlines(subset, chomp: true).map(&:strip).reject(&:empty?).to_set
          rpcs = rpcs.select { |name, _| allowlist.include?(name) }
          subset_note = "curated subset (#{rpcs.size} of #{total} RPCs in the dump)"
        end

        source = {
          "kind" => "broker_dump",
          "captured_at" => captured_at,
          "dat_sha" => dat_sha,
          "note" => [ note || "file 8994 export (#{File.basename(dump)})", subset_note ].compact.join("; ")
        }.compact
        source["inventory"] = inventory if inventory

        fingerprint = {
          "backend" => backend,
          "lineage" => LINEAGE.fetch(backend, "rpms"),
          "release" => release,
          "source" => source,
          "rpcs" => rpcs.sort.to_h,
          "packages" => package_versions,
          "patches" => [],
          "bmw_tables" => {}
        }

        via = inventory ? " via conformance:pin" : ""
        header = "# Fingerprint: #{env} — generated by `rake conformance:ingest`#{via}.\n"
        header << "# Source: file-8994 broker dump #{File.basename(dump)}, captured #{captured_at}.\n"
        if inventory
          header << "# Pinned rpms-ops build #{inventory['tag']} (#{inventory['rpms_version']}, engine #{inventory['engine']}, " \
                    "commit #{inventory['build_commit']}, artifact #{inventory['artifact_sha256']});\n"
          header << "# every line below is a registry entry from those exact bytes — see data/fingerprints/rpms-ops.lock.yml.\n"
        end
        if subset_note
          header << "# NOTE: #{subset_note} — representative, reviewable slice of the\n"
          header << "# real export; every line below is a real registry entry from the dump.\n"
        end
        if package_versions.empty?
          header << "# packages/patches/bmw_tables faces are empty until captured (follow-up).\n"
        else
          header << "# packages face: #{package_versions.size} PACKAGE #9.4 entries from #{File.basename(packages)}.\n"
          header << "# patches/bmw_tables faces are empty until captured (follow-up).\n"
        end

        out_path = File.join(fingerprints_dir, "#{env}.yml")
        FileUtils.mkdir_p(File.dirname(out_path))
        File.write(out_path, header + YAML.dump(fingerprint))
        { path: out_path, rpcs: rpcs.size, total: total, packages: package_versions.size, subset_note: subset_note }
      end
    end
  end
end
