# frozen_string_literal: true

require "set"
require "vista_rpc/data_mapper"

module RpmsRpc
  # Generates a markdown coverage matrix from VistaRpc::DataMapper definitions.
  #
  #   RpmsRpc::CoverageMatrix.new.generate  # => markdown string
  #   RpmsRpc::CoverageMatrix.new.write("docs/rpcs.md")
  #
  # The matrix columns are: namespace, RPC name, mapping status, M source
  # citation, test status, and backend (VA/VistA or RPMS/IHS).
  class CoverageMatrix
    TEST_DIRS = [
      File.expand_path("../../../vista-rpc/test", __dir__),
      File.expand_path("../../../lakeraven-ehr/test", __dir__),
      File.expand_path("../../test", __dir__)
    ].freeze

    def initialize(registry: VistaRpc::DataMapper.registry, test_index: nil)
      @registry = registry
      @test_index = test_index || build_test_index
    end

    def generate
      rows = sorted_mappings.map { |name, mapping| row_for(name, mapping) }

      <<~MARKDOWN
        # RPC Coverage Matrix

        Generated by `rake coverage:matrix` from `VistaRpc::DataMapper` definitions.

        | Namespace | RPC Name | Mapping Status | M Source | Test Status | Backend |
        | --- | --- | --- | --- | --- | --- |
        #{rows.map { |r| "| #{r.join(" | ")} |" }.join("\n")}

        ## Summary

        - Total mapped RPCs: #{rows.length}
        - VA/VistA: #{rows.count { |r| r[5] == "VA" }}
        - RPMS/IHS: #{rows.count { |r| r[5] == "RPMS" }}
        - Tested: #{rows.count { |r| r[4] == "tested" }}
        - Untested: #{rows.count { |r| r[4] == "untested" }}
        - M source verified: #{rows.count { |r| r[3] != "unverified" }}
        - M source unverified: #{rows.count { |r| r[3] == "unverified" }}
      MARKDOWN
    end

    def write(path)
      File.write(path, generate)
    end

    private

    def sorted_mappings
      @registry.sort_by { |name, mapping| [ namespace_for(mapping.rpc_name), mapping.rpc_name.to_s ] }
    end

    def row_for(name, mapping)
      rpc_name = mapping.rpc_name || name.to_s
      [
        namespace_for(rpc_name),
        "`#{rpc_name}`",
        mapping_status(mapping),
        source_for(mapping),
        test_status(name, rpc_name),
        backend_for(mapping.backend)
      ]
    end

    def namespace_for(rpc_name)
      rpc_name.to_s.split(/\s+/, 2).first.to_s.sub(/\A([A-Z]+).*\z/, "\\1")
    end

    def mapping_status(mapping)
      return "text-blob" if mapping.text_blob?
      return "scalar" if mapping.scalar?
      return "line-based" if mapping.instance_variable_defined?(:@line_fields) && !mapping.instance_variable_get(:@line_fields).nil?

      "field-mapped"
    end

    def source_for(mapping)
      mapping.source || "unverified"
    end

    def test_status(name, rpc_name)
      @test_index.include?(name.to_s) || @test_index.include?(rpc_name.to_s) ? "tested" : "untested"
    end

    def backend_for(backend)
      case backend
      when :rpms then "RPMS"
      when :vista, :va then "VA"
      else "unknown"
      end
    end

    def build_test_index
      index = Set.new
      TEST_DIRS.each do |dir|
        next unless Dir.exist?(dir)

        Dir.glob(File.join(dir, "**", "*_test.rb")).each do |path|
          content = File.read(path)
          content.scan(/[A-Z][A-Z0-9]+(?:\s+[A-Z][A-Z0-9]+)+/).each { |s| index << s.strip }
          content.scan(/DataMapper\[(?:"([^"]+)"|:([^\]]+))\]/).each do |match|
            index << (match[0] || match[1]).to_s
          end
          content.scan(/patient_select|patient_id_info|patient_list|practitioner_info|signon_setup|av_code/).each { |s| index << s }
        end
      end
      index
    end
  end
end
